env: "local"
http_server:
  address: "localhost:8010"
  timeout: 4s
  idle_timeout: 60s

redis_server:
  address: "localhost:6379"
  password: ""
  db: 0

postgres_data:
  address: "localhost:5432"
  name: "events_service_data"

jwt-secret: "vVerYsEEECre234TtoOoKkEnn"